In [50]:
import pandas as pd

In [51]:
df = pd.read_csv("raw_data.csv")

In [52]:
# Feature Engineering

df2 = df.copy()

# apply()
df2["tax"] = df2["income"].apply(lambda x : "20%" if x >= 50000 else "10%")


# map()
# Male => M, Female => F, Unknown => U
gender_map = {"Male" : "M", "Female" : "F", "Unknown" : "U"}
df2["gender"] = df2["gender"].map(gender_map)

# assign()
df2 = df2.assign(new_income = df2["income"] * 1.1)


# replace()
df2["country"] = df2["country"].replace("USA", "United States")

# rename()
df2.columns = ["Id", "Name", "Age", "Country", "Gender", "Income", "Tax", "New_Income"]
df2.rename(columns = {"Income" : "Salary"})

# sort()
df2.sort_values("Income")
df2.sort_values("Income", ascending=False)
sorted_df = df2.sort_values(["Income", "Age"])

sorted_df.sort_index()

# reset
sorted_df.reset_index()
sorted_df.reset_index(drop=True)

# Ranking - rank()
sorted_df["Ranking"] = sorted_df["Income"].rank()
sorted_df["Ranking"] = sorted_df["Income"].rank(ascending=False)
sorted_df["Ranking"] = sorted_df["Income"].rank(ascending=False, method="dense")
sorted_df["Ranking"] = sorted_df["Income"].rank(ascending=False, method="min")
sorted_df["Ranking"] = sorted_df["Income"].rank(ascending=False, method="max")

# Reorder Columns
sorted_df[["Id", "Name", "Age", "Country", "Gender", "Income", "New_Income", "Tax"]]

    Id          Name   Age        Country Gender   Income  New_Income  Tax
9    9   Carlos Ruiz   NaN         Mexico      M  45000.0     49500.0  10%
3    3          Alex   NaN  United States      U  47000.0     51700.0  10%
5    5        Li Wei  27.0          China      M  51000.0     56100.0  20%
0    1      John Doe  29.0  United States      M  55000.0     60500.0  20%
1    1      John Doe  29.0  United States      M  55000.0     60500.0  20%
10  10   Emily Davis  31.0  United States    NaN  58000.0     63800.0  20%
8    8    Rachel Lee  29.0  United States      F  62000.0     68200.0  20%
2    2    Jane Smith   NaN         Canada      F  62000.0     68200.0  20%
7    7    Ahmed Khan  38.0            NaN      M  68000.0     74800.0  20%
6    6           NaN  45.0          India      F  73000.0     80300.0  20%
4    4  Maria Garcia  34.0          Spain      F      NaN         NaN  10%

In [54]:
df2 = df.copy()

# new_col_order = ["name", "age", "country", "gender", "income", "id"]
new_col_order = [col for col in df2.columns if col != "id"] + ["id"]
# new_col_order
df2[new_col_order]

            name   age country   gender   income  id
0       John Doe  29.0     USA     Male  55000.0   1
1       John Doe  29.0     USA     Male  55000.0   1
2     Jane Smith   NaN  Canada   Female  62000.0   2
3           Alex   NaN     USA  Unknown  47000.0   3
4   Maria Garcia  34.0   Spain   Female      NaN   4
5         Li Wei  27.0   China     Male  51000.0   5
6            NaN  45.0   India   Female  73000.0   6
7     Ahmed Khan  38.0     NaN     Male  68000.0   7
8     Rachel Lee  29.0     USA   Female  62000.0   8
9    Carlos Ruiz   NaN  Mexico     Male  45000.0   9
10   Emily Davis  31.0     USA      NaN  58000.0  10